# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Second_Enviando.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        self.txt_a = QtWidgets.QLineEdit(Dialog)
        self.txt_a.setGeometry(QtCore.QRect(130, 40, 201, 51))
        self.txt_a.setStyleSheet("font: 9pt \"Yu Gothic UI\";")
        self.txt_a.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_a.setObjectName("txt_a")
        self.txt_b = QtWidgets.QLineEdit(Dialog)
        self.txt_b.setGeometry(QtCore.QRect(130, 110, 201, 51))
        self.txt_b.setStyleSheet("font: 9pt \"Yu Gothic UI\";")
        self.txt_b.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_b.setObjectName("txt_b")
        self.btn_sumar = QtWidgets.QPushButton(Dialog)
        self.btn_sumar.setGeometry(QtCore.QRect(160, 190, 93, 28))
        self.btn_sumar.setObjectName("btn_sumar")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 55, 16))
        self.label_2.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 60, 55, 16))
        self.label.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_sumar.setText(_translate("Dialog", "Sumar"))
        self.label_2.setText(_translate("Dialog", "B:"))
        self.label.setText(_translate("Dialog", "A:"))
