# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_03_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 557)
        MainWindow.setStyleSheet("background-color: rgb(250, 215, 160);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_fit = QtWidgets.QLabel(self.centralwidget)
        self.img_fit.setGeometry(QtCore.QRect(350, 0, 191, 71))
        self.img_fit.setText("")
        self.img_fit.setPixmap(QtGui.QPixmap(":/logos/logo fit.png"))
        self.img_fit.setScaledContents(True)
        self.img_fit.setObjectName("img_fit")
        self.img_logo = QtWidgets.QLabel(self.centralwidget)
        self.img_logo.setGeometry(QtCore.QRect(460, 430, 71, 71))
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap(":/logos/Imagenes/logoCT.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setObjectName("img_logo")
        self.img_uat = QtWidgets.QLabel(self.centralwidget)
        self.img_uat.setGeometry(QtCore.QRect(0, 0, 181, 71))
        self.img_uat.setText("")
        self.img_uat.setPixmap(QtGui.QPixmap(":/logos/logo uat.png"))
        self.img_uat.setScaledContents(True)
        self.img_uat.setObjectName("img_uat")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 240, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(210, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_ok.setObjectName("btn_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Usted pagará su producto durante 12 meses"))
        self.btn_ok.setText(_translate("MainWindow", "Ok"))
import recursos_rc
