# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'costo_viajes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 289)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_resultado = QtWidgets.QLabel(Dialog)
        self.txt_resultado.setGeometry(QtCore.QRect(40, 100, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setText("")
        self.txt_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado.setObjectName("txt_resultado")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_resultado_2 = QtWidgets.QLabel(Dialog)
        self.txt_resultado_2.setGeometry(QtCore.QRect(260, 100, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_resultado_2.setFont(font)
        self.txt_resultado_2.setText("")
        self.txt_resultado_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado_2.setObjectName("txt_resultado_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Costo del viaje"))
        self.label_3.setText(_translate("Dialog", "Costo por persona"))
