# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_viajes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_personas = QtWidgets.QLineEdit(self.centralwidget)
        self.line_personas.setGeometry(QtCore.QRect(230, 220, 151, 31))
        self.line_personas.setObjectName("line_personas")
        self.line_km = QtWidgets.QLineEdit(self.centralwidget)
        self.line_km.setGeometry(QtCore.QRect(230, 150, 151, 31))
        self.line_km.setObjectName("line_km")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.combo_bus = QtWidgets.QComboBox(self.centralwidget)
        self.combo_bus.setGeometry(QtCore.QRect(240, 90, 131, 21))
        self.combo_bus.setObjectName("combo_bus")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_continuar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_continuar.setGeometry(QtCore.QRect(380, 280, 151, 41))
        self.btn_continuar.setObjectName("btn_continuar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Km a reccorer"))
        self.label_3.setText(_translate("MainWindow", "Numero de personas"))
        self.label_4.setText(_translate("MainWindow", "Tipo de autobus"))
        self.btn_continuar.setText(_translate("MainWindow", "Continuar"))
