# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minimoPersonas_viajes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 331, 71))
        self.textEdit.setObjectName("textEdit")
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar.setGeometry(QtCore.QRect(50, 220, 141, 31))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_continuar = QtWidgets.QPushButton(Dialog)
        self.btn_continuar.setGeometry(QtCore.QRect(210, 220, 141, 31))
        self.btn_continuar.setObjectName("btn_continuar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Minimo debe haber 20 personas en el camion de lo contrario se te cobrara con base en este numero limite.</span></p></body></html>"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar viaje"))
        self.btn_continuar.setText(_translate("Dialog", "Continuar"))
