# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_05_Stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 848)
        MainWindow.setStyleSheet("background-color: rgb(81, 124, 166);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_logoUAT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoUAT.setGeometry(QtCore.QRect(30, 10, 181, 71))
        self.lbl_logoUAT.setText("")
        self.lbl_logoUAT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/UAT-Escudo-2024.png"))
        self.lbl_logoUAT.setScaledContents(True)
        self.lbl_logoUAT.setObjectName("lbl_logoUAT")
        self.lbl_logoFIT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoFIT.setGeometry(QtCore.QRect(540, 20, 211, 61))
        self.lbl_logoFIT.setText("")
        self.lbl_logoFIT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/LogoFIT.png"))
        self.lbl_logoFIT.setScaledContents(True)
        self.lbl_logoFIT.setObjectName("lbl_logoFIT")
        self.lbl_logoCT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoCT.setGeometry(QtCore.QRect(700, 750, 71, 51))
        self.lbl_logoCT.setText("")
        self.lbl_logoCT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/logoCT.png"))
        self.lbl_logoCT.setScaledContents(True)
        self.lbl_logoCT.setObjectName("lbl_logoCT")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(75, 120, 631, 661))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 1px solid black;\n"
"border-radius: 25px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 50, 261, 81))
        self.label_9.setStyleSheet("font: 20pt \"Yu Gothic UI\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 130, 601, 631))
        self.frame.setMinimumSize(QtCore.QSize(601, 291))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 601, 621))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(1, 0, 0, 22)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(36)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_stock1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock1.setText("")
        self.lbl_stock1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock1.setObjectName("lbl_stock1")
        self.gridLayout.addWidget(self.lbl_stock1, 2, 1, 1, 1)
        self.lbl_sold2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold2.setObjectName("lbl_sold2")
        self.gridLayout.addWidget(self.lbl_sold2, 3, 2, 1, 1)
        self.lbl_sold1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold1.setObjectName("lbl_sold1")
        self.gridLayout.addWidget(self.lbl_sold1, 2, 2, 1, 1)
        self.lbl_sold3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold3.setObjectName("lbl_sold3")
        self.gridLayout.addWidget(self.lbl_sold3, 4, 2, 1, 1)
        self.lbl_restock1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock1.setObjectName("lbl_restock1")
        self.gridLayout.addWidget(self.lbl_restock1, 2, 3, 1, 1)
        self.lbl_restock2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock2.setObjectName("lbl_restock2")
        self.gridLayout.addWidget(self.lbl_restock2, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.lbl_stock2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock2.setText("")
        self.lbl_stock2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock2.setObjectName("lbl_stock2")
        self.gridLayout.addWidget(self.lbl_stock2, 3, 1, 1, 1)
        self.btn_buy1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy1.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy1.setObjectName("btn_buy1")
        self.gridLayout.addWidget(self.btn_buy1, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 4, 1, 1)
        self.lbl_stock3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock3.setText("")
        self.lbl_stock3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock3.setObjectName("lbl_stock3")
        self.gridLayout.addWidget(self.lbl_stock3, 4, 1, 1, 1)
        self.lbl_restock3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock3.setObjectName("lbl_restock3")
        self.gridLayout.addWidget(self.lbl_restock3, 4, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 8pt \"Yu Gothic UI\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.btn_buy2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy2.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy2.setObjectName("btn_buy2")
        self.gridLayout.addWidget(self.btn_buy2, 3, 4, 1, 1)
        self.btn_buy3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy3.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy3.setObjectName("btn_buy3")
        self.gridLayout.addWidget(self.btn_buy3, 4, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 9, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 11, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 10, 0, 1, 1)
        self.lbl_stock4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock4.setText("")
        self.lbl_stock4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock4.setObjectName("lbl_stock4")
        self.gridLayout.addWidget(self.lbl_stock4, 5, 1, 1, 1)
        self.lbl_stock5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock5.setText("")
        self.lbl_stock5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock5.setObjectName("lbl_stock5")
        self.gridLayout.addWidget(self.lbl_stock5, 6, 1, 1, 1)
        self.lbl_stock6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock6.setText("")
        self.lbl_stock6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock6.setObjectName("lbl_stock6")
        self.gridLayout.addWidget(self.lbl_stock6, 7, 1, 1, 1)
        self.lbl_stock7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock7.setText("")
        self.lbl_stock7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock7.setObjectName("lbl_stock7")
        self.gridLayout.addWidget(self.lbl_stock7, 8, 1, 1, 1)
        self.lbl_stock8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock8.setText("")
        self.lbl_stock8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock8.setObjectName("lbl_stock8")
        self.gridLayout.addWidget(self.lbl_stock8, 9, 1, 1, 1)
        self.lbl_stock9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock9.setText("")
        self.lbl_stock9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock9.setObjectName("lbl_stock9")
        self.gridLayout.addWidget(self.lbl_stock9, 10, 1, 1, 1)
        self.lbl_stock10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_stock10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_stock10.setText("")
        self.lbl_stock10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stock10.setObjectName("lbl_stock10")
        self.gridLayout.addWidget(self.lbl_stock10, 11, 1, 1, 1)
        self.lbl_sold4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold4.setObjectName("lbl_sold4")
        self.gridLayout.addWidget(self.lbl_sold4, 5, 2, 1, 1)
        self.lbl_sold5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold5.setObjectName("lbl_sold5")
        self.gridLayout.addWidget(self.lbl_sold5, 6, 2, 1, 1)
        self.lbl_sold6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold6.setObjectName("lbl_sold6")
        self.gridLayout.addWidget(self.lbl_sold6, 7, 2, 1, 1)
        self.lbl_sold7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold7.setObjectName("lbl_sold7")
        self.gridLayout.addWidget(self.lbl_sold7, 8, 2, 1, 1)
        self.lbl_sold8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold8.setObjectName("lbl_sold8")
        self.gridLayout.addWidget(self.lbl_sold8, 9, 2, 1, 1)
        self.lbl_sold9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold9.setObjectName("lbl_sold9")
        self.gridLayout.addWidget(self.lbl_sold9, 10, 2, 1, 1)
        self.lbl_sold10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_sold10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_sold10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sold10.setObjectName("lbl_sold10")
        self.gridLayout.addWidget(self.lbl_sold10, 11, 2, 1, 1)
        self.lbl_restock4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock4.setObjectName("lbl_restock4")
        self.gridLayout.addWidget(self.lbl_restock4, 5, 3, 1, 1)
        self.lbl_restock5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock5.setObjectName("lbl_restock5")
        self.gridLayout.addWidget(self.lbl_restock5, 6, 3, 1, 1)
        self.lbl_restock6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock6.setObjectName("lbl_restock6")
        self.gridLayout.addWidget(self.lbl_restock6, 7, 3, 1, 1)
        self.lbl_restock7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock7.setObjectName("lbl_restock7")
        self.gridLayout.addWidget(self.lbl_restock7, 8, 3, 1, 1)
        self.lbl_restock8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock8.setObjectName("lbl_restock8")
        self.gridLayout.addWidget(self.lbl_restock8, 9, 3, 1, 1)
        self.lbl_restock9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock9.setObjectName("lbl_restock9")
        self.gridLayout.addWidget(self.lbl_restock9, 10, 3, 1, 1)
        self.lbl_restock10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_restock10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.lbl_restock10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_restock10.setObjectName("lbl_restock10")
        self.gridLayout.addWidget(self.lbl_restock10, 11, 3, 1, 1)
        self.btn_buy4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy4.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy4.setObjectName("btn_buy4")
        self.gridLayout.addWidget(self.btn_buy4, 5, 4, 1, 1)
        self.btn_buy5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy5.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy5.setObjectName("btn_buy5")
        self.gridLayout.addWidget(self.btn_buy5, 6, 4, 1, 1)
        self.btn_buy6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy6.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy6.setObjectName("btn_buy6")
        self.gridLayout.addWidget(self.btn_buy6, 7, 4, 1, 1)
        self.btn_buy7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy7.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy7.setObjectName("btn_buy7")
        self.gridLayout.addWidget(self.btn_buy7, 8, 4, 1, 1)
        self.btn_buy8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy8.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy8.setObjectName("btn_buy8")
        self.gridLayout.addWidget(self.btn_buy8, 9, 4, 1, 1)
        self.btn_buy9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy9.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy9.setObjectName("btn_buy9")
        self.gridLayout.addWidget(self.btn_buy9, 10, 4, 1, 1)
        self.btn_buy10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_buy10.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy10.setObjectName("btn_buy10")
        self.gridLayout.addWidget(self.btn_buy10, 11, 4, 1, 1)
        self.label_9.raise_()
        self.label_2.raise_()
        self.lbl_logoUAT.raise_()
        self.lbl_logoFIT.raise_()
        self.lbl_logoCT.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Almacen"))
        self.lbl_sold2.setText(_translate("MainWindow", "0"))
        self.lbl_sold1.setText(_translate("MainWindow", "0"))
        self.lbl_sold3.setText(_translate("MainWindow", "0"))
        self.lbl_restock1.setText(_translate("MainWindow", "0"))
        self.lbl_restock2.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "ReStock"))
        self.label_12.setText(_translate("MainWindow", "Doritos Nacho 53gr."))
        self.label_7.setText(_translate("MainWindow", "CocaCola 600ml."))
        self.label_10.setText(_translate("MainWindow", "Vendidas"))
        self.label_13.setText(_translate("MainWindow", "Existencia"))
        self.label_11.setText(_translate("MainWindow", "Gansito"))
        self.btn_buy1.setText(_translate("MainWindow", "Comprar"))
        self.label_15.setText(_translate("MainWindow", "Accion"))
        self.lbl_restock3.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Productos"))
        self.btn_buy2.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy3.setText(_translate("MainWindow", "Comprar"))
        self.label_20.setText(_translate("MainWindow", "Piñada 600ml."))
        self.label_21.setText(_translate("MainWindow", "Chips Fuego 50gr."))
        self.label_16.setText(_translate("MainWindow", "Pepsi 600ml."))
        self.label_19.setText(_translate("MainWindow", "Emperador Limon"))
        self.label_17.setText(_translate("MainWindow", "Mazapan 15gr."))
        self.label_18.setText(_translate("MainWindow", "Doritos Dinamita 45g."))
        self.label_22.setText(_translate("MainWindow", "Jumex 300ml."))
        self.lbl_sold4.setText(_translate("MainWindow", "0"))
        self.lbl_sold5.setText(_translate("MainWindow", "0"))
        self.lbl_sold6.setText(_translate("MainWindow", "0"))
        self.lbl_sold7.setText(_translate("MainWindow", "0"))
        self.lbl_sold8.setText(_translate("MainWindow", "0"))
        self.lbl_sold9.setText(_translate("MainWindow", "0"))
        self.lbl_sold10.setText(_translate("MainWindow", "0"))
        self.lbl_restock4.setText(_translate("MainWindow", "0"))
        self.lbl_restock5.setText(_translate("MainWindow", "0"))
        self.lbl_restock6.setText(_translate("MainWindow", "0"))
        self.lbl_restock7.setText(_translate("MainWindow", "0"))
        self.lbl_restock8.setText(_translate("MainWindow", "0"))
        self.lbl_restock9.setText(_translate("MainWindow", "0"))
        self.lbl_restock10.setText(_translate("MainWindow", "0"))
        self.btn_buy4.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy5.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy6.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy7.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy8.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy9.setText(_translate("MainWindow", "Comprar"))
        self.btn_buy10.setText(_translate("MainWindow", "Comprar"))
import recursos_rc
