# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_05_StockDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 434)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(81, 124, 166);")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 261, 81))
        self.label_2.setStyleSheet("font: 20pt \"Yu Gothic UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 120, 481, 231))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 1px solid black;\n"
"border-radius: 25px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.txt_cantidad = QtWidgets.QLineEdit(Dialog)
        self.txt_cantidad.setGeometry(QtCore.QRect(355, 179, 81, 24))
        self.txt_cantidad.setAccessibleDescription("")
        self.txt_cantidad.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_cantidad.setInputMask("")
        self.txt_cantidad.setText("")
        self.txt_cantidad.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cantidad.setObjectName("txt_cantidad")
        self.lbl_producto = QtWidgets.QLabel(Dialog)
        self.lbl_producto.setGeometry(QtCore.QRect(135, 180, 171, 20))
        self.lbl_producto.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_producto.setText("")
        self.lbl_producto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_producto.setObjectName("lbl_producto")
        self.btn_buy = QtWidgets.QPushButton(Dialog)
        self.btn_buy.setGeometry(QtCore.QRect(240, 260, 121, 41))
        self.btn_buy.setStyleSheet("font: 10pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_buy.setObjectName("btn_buy")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 150, 131, 20))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 8pt \"Yu Gothic UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_4.raise_()
        self.label_2.raise_()
        self.txt_cantidad.raise_()
        self.lbl_producto.raise_()
        self.btn_buy.raise_()
        self.label_5.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Venta"))
        self.txt_cantidad.setPlaceholderText(_translate("Dialog", "0"))
        self.btn_buy.setText(_translate("Dialog", "Comprar"))
        self.label_5.setText(_translate("Dialog", "Cantidad"))
