# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_00_EjecutableGeneral.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_logoUAT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoUAT.setGeometry(QtCore.QRect(30, 10, 181, 71))
        self.lbl_logoUAT.setText("")
        self.lbl_logoUAT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/UAT-Escudo-2024.png"))
        self.lbl_logoUAT.setScaledContents(True)
        self.lbl_logoUAT.setObjectName("lbl_logoUAT")
        self.lbl_logoFIT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoFIT.setGeometry(QtCore.QRect(410, 20, 211, 61))
        self.lbl_logoFIT.setText("")
        self.lbl_logoFIT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/LogoFIT.png"))
        self.lbl_logoFIT.setScaledContents(True)
        self.lbl_logoFIT.setObjectName("lbl_logoFIT")
        self.lbl_logoCT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoCT.setGeometry(QtCore.QRect(570, 360, 71, 51))
        self.lbl_logoCT.setText("")
        self.lbl_logoCT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/logoCT.png"))
        self.lbl_logoCT.setScaledContents(True)
        self.lbl_logoCT.setObjectName("lbl_logoCT")
        self.btn_ej5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ej5.setGeometry(QtCore.QRect(230, 220, 191, 41))
        self.btn_ej5.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.btn_ej5.setObjectName("btn_ej5")
        self.btn_ej6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ej6.setGeometry(QtCore.QRect(230, 270, 191, 41))
        self.btn_ej6.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.btn_ej6.setObjectName("btn_ej6")
        self.btn_ej4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ej4.setGeometry(QtCore.QRect(230, 170, 191, 41))
        self.btn_ej4.setStyleSheet("font: 10pt \"Yu Gothic UI\";")
        self.btn_ej4.setObjectName("btn_ej4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ej5.setText(_translate("MainWindow", "Ejercicio 5"))
        self.btn_ej6.setText(_translate("MainWindow", "Ejercicio 6"))
        self.btn_ej4.setText(_translate("MainWindow", "Ejercicio 4"))
import recursos_rc
