# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_04_TrabajoXHoraDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(481, 464)
        Dialog.setStyleSheet("background-color: rgb(81, 124, 166);")
        self.txt_1 = QtWidgets.QLineEdit(Dialog)
        self.txt_1.setGeometry(QtCore.QRect(250, 149, 100, 24))
        self.txt_1.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_1.setText("")
        self.txt_1.setReadOnly(True)
        self.txt_1.setObjectName("txt_1")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 150, 111, 20))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.txt_4 = QtWidgets.QLineEdit(Dialog)
        self.txt_4.setGeometry(QtCore.QRect(250, 269, 100, 24))
        self.txt_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Verdana\";")
        self.txt_4.setText("")
        self.txt_4.setReadOnly(True)
        self.txt_4.setObjectName("txt_4")
        self.txt_2 = QtWidgets.QLineEdit(Dialog)
        self.txt_2.setGeometry(QtCore.QRect(250, 189, 100, 24))
        self.txt_2.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_2.setText("")
        self.txt_2.setReadOnly(True)
        self.txt_2.setObjectName("txt_2")
        self.txt_5 = QtWidgets.QLineEdit(Dialog)
        self.txt_5.setGeometry(QtCore.QRect(250, 309, 100, 24))
        self.txt_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Verdana\";")
        self.txt_5.setText("")
        self.txt_5.setReadOnly(True)
        self.txt_5.setObjectName("txt_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 190, 111, 20))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(130, 270, 111, 20))
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(130, 310, 111, 20))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_8.setObjectName("label_8")
        self.txt_3 = QtWidgets.QLineEdit(Dialog)
        self.txt_3.setGeometry(QtCore.QRect(250, 229, 100, 24))
        self.txt_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Verdana\";")
        self.txt_3.setText("")
        self.txt_3.setReadOnly(True)
        self.txt_3.setObjectName("txt_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(130, 230, 111, 20))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.txt_total = QtWidgets.QLineEdit(Dialog)
        self.txt_total.setGeometry(QtCore.QRect(236, 366, 101, 31))
        self.txt_total.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Yu Gothic UI\";")
        self.txt_total.setReadOnly(True)
        self.txt_total.setObjectName("txt_total")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 370, 111, 20))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 10pt \"Yu Gothic UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 40, 261, 81))
        self.label_2.setStyleSheet("font: 20pt \"Yu Gothic UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 120, 311, 301))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 1px solid black;\n"
"border-radius: 25px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.txt_1.raise_()
        self.label_3.raise_()
        self.txt_4.raise_()
        self.txt_2.raise_()
        self.txt_5.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.txt_3.raise_()
        self.label_6.raise_()
        self.txt_total.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Empleado 1:"))
        self.label_5.setText(_translate("Dialog", "Empleado 2:"))
        self.label_7.setText(_translate("Dialog", "Empleado 4:"))
        self.label_8.setText(_translate("Dialog", "Empleado 5:"))
        self.label_6.setText(_translate("Dialog", "Empleado 3:"))
        self.label.setText(_translate("Dialog", "Total:"))
        self.label_2.setText(_translate("Dialog", "Sueldo Semanal"))
