# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_04_TrabajoXHora.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 619)
        MainWindow.setStyleSheet("background-color: rgb(81, 124, 166);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_logoUAT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoUAT.setGeometry(QtCore.QRect(30, 10, 181, 71))
        self.lbl_logoUAT.setText("")
        self.lbl_logoUAT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/UAT-Escudo-2024.png"))
        self.lbl_logoUAT.setScaledContents(True)
        self.lbl_logoUAT.setObjectName("lbl_logoUAT")
        self.lbl_logoFIT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoFIT.setGeometry(QtCore.QRect(410, 20, 211, 61))
        self.lbl_logoFIT.setText("")
        self.lbl_logoFIT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/LogoFIT.png"))
        self.lbl_logoFIT.setScaledContents(True)
        self.lbl_logoFIT.setObjectName("lbl_logoFIT")
        self.lbl_logoCT = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logoCT.setGeometry(QtCore.QRect(570, 520, 71, 51))
        self.lbl_logoCT.setText("")
        self.lbl_logoCT.setPixmap(QtGui.QPixmap(":/logo/Imagenes/logoCT.png"))
        self.lbl_logoCT.setScaledContents(True)
        self.lbl_logoCT.setObjectName("lbl_logoCT")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 439, 141, 20))
        self.label.setStyleSheet("font: 10pt \"Yu Gothic UI\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.txt_salario = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_salario.setGeometry(QtCore.QRect(256, 435, 101, 31))
        self.txt_salario.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_salario.setObjectName("txt_salario")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 230, 111, 20))
        self.label_3.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.txt_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_1.setGeometry(QtCore.QRect(290, 229, 81, 24))
        self.txt_1.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_1.setText("")
        self.txt_1.setObjectName("txt_1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(275, 200, 111, 20))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 8pt \"Yu Gothic UI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(420, 359, 121, 41))
        self.btn_calcular.setStyleSheet("font: 10pt \"Yu Gothic UI\";\n"
"background-color: rgb(206, 206, 206);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.btn_calcular.setObjectName("btn_calcular")
        self.txt_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_2.setGeometry(QtCore.QRect(290, 269, 81, 24))
        self.txt_2.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_2.setText("")
        self.txt_2.setObjectName("txt_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 270, 111, 20))
        self.label_5.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.txt_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_3.setGeometry(QtCore.QRect(290, 309, 81, 24))
        self.txt_3.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_3.setText("")
        self.txt_3.setObjectName("txt_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 310, 111, 20))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.txt_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_4.setGeometry(QtCore.QRect(290, 349, 81, 24))
        self.txt_4.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_4.setText("")
        self.txt_4.setObjectName("txt_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 350, 111, 20))
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_7.setObjectName("label_7")
        self.txt_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_5.setGeometry(QtCore.QRect(290, 389, 81, 24))
        self.txt_5.setStyleSheet("font: 9pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_5.setText("")
        self.txt_5.setObjectName("txt_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 390, 111, 20))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 9pt \"Verdana\";")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(55, 179, 541, 311))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 1px solid black;\n"
"border-radius: 25px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 90, 261, 81))
        self.label_9.setStyleSheet("font: 20pt \"Yu Gothic UI\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_2.raise_()
        self.lbl_logoUAT.raise_()
        self.lbl_logoFIT.raise_()
        self.lbl_logoCT.raise_()
        self.label.raise_()
        self.txt_salario.raise_()
        self.label_3.raise_()
        self.txt_1.raise_()
        self.label_4.raise_()
        self.btn_calcular.raise_()
        self.txt_2.raise_()
        self.label_5.raise_()
        self.txt_3.raise_()
        self.label_6.raise_()
        self.txt_4.raise_()
        self.label_7.raise_()
        self.txt_5.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Salario por Hora:"))
        self.label_3.setText(_translate("MainWindow", "Empleado 1:"))
        self.label_4.setText(_translate("MainWindow", "Horas"))
        self.btn_calcular.setText(_translate("MainWindow", "Calcular"))
        self.label_5.setText(_translate("MainWindow", "Empleado 2:"))
        self.label_6.setText(_translate("MainWindow", "Empleado 3:"))
        self.label_7.setText(_translate("MainWindow", "Empleado 4:"))
        self.label_8.setText(_translate("MainWindow", "Empleado 5:"))
        self.label_9.setText(_translate("MainWindow", "Trabajo Semanal"))
import recursos_rc
