# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Second_enviando.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 50, 151, 31))
        self.label.setStyleSheet("font: 10pt \"Yu Gothic UI\";\n"
"")
        self.label.setObjectName("label")
        self.lbl_resultado = QtWidgets.QLabel(Dialog)
        self.lbl_resultado.setGeometry(QtCore.QRect(80, 100, 261, 31))
        self.lbl_resultado.setStyleSheet("font: 9pt \"Yu Gothic UI\";\n"
"")
        self.lbl_resultado.setText("")
        self.lbl_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resultado.setObjectName("lbl_resultado")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Resultado:"))
