# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E8_Vinicultores.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 294)
        self.cb_tamano = QtWidgets.QComboBox(Dialog)
        self.cb_tamano.setGeometry(QtCore.QRect(120, 200, 111, 22))
        self.cb_tamano.setObjectName("cb_tamano")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 81, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txt_final = QtWidgets.QLineEdit(Dialog)
        self.txt_final.setGeometry(QtCore.QRect(282, 200, 121, 20))
        self.txt_final.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_final.setObjectName("txt_final")
        self.cb_tipo = QtWidgets.QComboBox(Dialog)
        self.cb_tipo.setGeometry(QtCore.QRect(120, 160, 111, 22))
        self.cb_tipo.setObjectName("cb_tipo")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(300, 180, 91, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 71, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 80, 81, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 91, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.btn_calcular = QtWidgets.QPushButton(Dialog)
        self.btn_calcular.setGeometry(QtCore.QRect(280, 120, 121, 41))
        self.btn_calcular.setObjectName("btn_calcular")
        self.txt_inicial = QtWidgets.QLineEdit(Dialog)
        self.txt_inicial.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.txt_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_inicial.setObjectName("txt_inicial")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Precio (Kg) uva:"))
        self.label_3.setText(_translate("Dialog", "Precio Final (Kg):"))
        self.label_4.setText(_translate("Dialog", "Tipo de uva:"))
        self.label.setText(_translate("Dialog", "Vinicultores"))
        self.label_5.setText(_translate("Dialog", "Tamaño de uva:"))
        self.btn_calcular.setText(_translate("Dialog", "Calcular"))
