# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E9_ViajeDeEstudios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(394, 346)
        self.txt_cobrar = QtWidgets.QLineEdit(Dialog)
        self.txt_cobrar.setGeometry(QtCore.QRect(70, 270, 113, 20))
        self.txt_cobrar.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cobrar.setObjectName("txt_cobrar")
        self.btn_calcular = QtWidgets.QPushButton(Dialog)
        self.btn_calcular.setGeometry(QtCore.QRect(90, 190, 241, 31))
        self.btn_calcular.setObjectName("btn_calcular")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 250, 151, 20))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 131, 21))
        self.label.setObjectName("label")
        self.txt_pagar = QtWidgets.QLineEdit(Dialog)
        self.txt_pagar.setGeometry(QtCore.QRect(230, 270, 113, 20))
        self.txt_pagar.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_pagar.setObjectName("txt_pagar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 250, 91, 20))
        self.label_3.setObjectName("label_3")
        self.txt_asistentes = QtWidgets.QLineEdit(Dialog)
        self.txt_asistentes.setGeometry(QtCore.QRect(200, 140, 113, 20))
        self.txt_asistentes.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_asistentes.setObjectName("txt_asistentes")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_calcular.setText(_translate("Dialog", "Calcular"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Debe de pagar por el servicio:</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">N° de asistentes:</p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Viaje de estudios</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Debe de cobrar:</p></body></html>"))
