# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ejercicios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 71, 16))
        self.label.setObjectName("label")
        self.btn_ejercicio8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio8.setGeometry(QtCore.QRect(180, 220, 121, 41))
        self.btn_ejercicio8.setObjectName("btn_ejercicio8")
        self.btn_ejercicio9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio9.setGeometry(QtCore.QRect(180, 280, 121, 41))
        self.btn_ejercicio9.setObjectName("btn_ejercicio9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ejercicios"))
        self.btn_ejercicio8.setText(_translate("MainWindow", "Ejercicio 8"))
        self.btn_ejercicio9.setText(_translate("MainWindow", "Ejercicio 9"))
