# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E_07_Langosta_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 289)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_resultado = QtWidgets.QLabel(Dialog)
        self.txt_resultado.setGeometry(QtCore.QRect(150, 110, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setText("")
        self.txt_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado.setObjectName("txt_resultado")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Presupuesto del evento"))
